import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/molecules/Header/Header";
import { HeaderPropsType } from "@/types";
import HeaderIcon from "@/components/icons/HeaderIcon";
import SearchIcon from "@/components/icons/SearchIcon";
import WishlistIcon from "@/components/icons/WishlistIcon";
import CartIcon from "@/components/icons/CartIcon";
import MainHeaderIcon from "@/components/icons/MainHeaderIcon";
import HamburgerIcon from "@/components/icons/HamburgerIcon";
import ProfileIcon from "@/components/icons/ProfileIcon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerData: HeaderPropsType = {
  topHeaderData: {
    logo: {
      img: <HeaderIcon />,
      altText: "top-header-logo",
      redirectTo: "",
    },
    navItems: [
      {
        text: "Find a Store",
        redirectTo: "/store",
      },
      {
        text: "Help",
        redirectTo: "/help",
      },
      {
        text: "Join Us",
        redirectTo: "/join-us",
      },
      {
        text: "Sign in",
        redirectTo: "/sign-in",
      },
    ],
  },
  categoryHeaderData: {
    mainLogo: {
      img: <MainHeaderIcon />,
      altText: "main-header-icon",
      redirectTo: "",
    },
    navItems: [
      {
        text: "New & Featured",
        redirectTo: "/new",
        subcategories: [
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
        ],
      },
      {
        text: "Men",
        redirectTo: "/men",
        subcategories: [
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
        ],
      },
      {
        text: "Women",
        redirectTo: "/women",
        subcategories: [
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
        ],
      },
      {
        text: "Kids",
        redirectTo: "/kids",
        subcategories: [
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
          {
            text: "Featured",
            redirectTo: "/featured",
            childSubcategories: [
              {
                text: "New & Upcoming Drops",
                redirectTo: "/new-upcoming-drops",
              },
              {
                text: "New Arrivals",
                redirectTo: "/new-upcoming-drops",
              },
            ],
          },
        ],
      },
    ],
    icons: [
      {
        img: <SearchIcon />,
        altText: "search-icon",
        redirectTo: "",
      },
      {
        img: <WishlistIcon />,
        altText: "wishlist-icon",
        redirectTo: "/wishlist",
      },
      {
        img: <CartIcon />,
        altText: "cart-icon",
        redirectTo: "/cart",
      },
      {
        img: <ProfileIcon />,
        altText: "profile-icon",
        redirectTo: "",
      },
      {
        img: <HamburgerIcon />,
        altText: "hamburger-icon",
        redirectTo: "",
      },
    ],
  },
  saleData: {
    title: "New Styles On Sale: Up To 40% Off",
    subtext: "Shop All Our New Markdowns",
    redirectTo: "/sale-3y3up",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header {...headerData} />
        {children}
      </body>
    </html>
  );
}
